
apiVersion: v1
kind: Service
metadata:
  name: kube-deploy-service
spec:
  type: NodePort
  selector:
    app: kube-deploy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007
