apiVersion: v1
kind: ConfigMap
metadata:
  name: streaming-nginx-config
data:
  nginx.conf: |
    worker_processes auto;

    events {
      worker_connections 1024;
    }

    rtmp {
      server {
        listen 1935;
        chunk_size 4096;

        application live {
          live on;
          record off;

          hls on;
          hls_path /tmp/hls/live;
          hls_fragment 3;
          hls_playlist_length 60;
        }
      }
    }

    http {
      include /etc/nginx/mime.types;
      default_type application/octet-stream;
      sendfile on;

      server {
        listen 8080;

        location /live {
          types {
            application/vnd.apple.mpegurl m3u8;
            video/mp2t ts;
          }
          root /tmp/hls;
          add_header Cache-Control no-cache;
        }
      }
    }
